# Generated by Django 4.2.23 on 2025-09-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE blog_comment
                DROP COLUMN IF EXISTS challenge;
            """,
            reverse_sql="""
                ALTER TABLE blog_comment
                ADD COLUMN IF NOT EXISTS challenge varchar NULL;
            """,
        ),
    ]
